services:
  mysql:
    image: mysql:5.7.36
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/sql:/opt/sql
    ports:
      - "3306:3306"
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456
  nacos:
    image: nacos/nacos-server:v2.1.1
    restart: always
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - MODE=standalone