server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: short-link-admin
          uri: lb://short-link-admin/api/short-link/admin/**
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            - name: TokenValidate
              args:
                whiteList:
                  - path: /api/short-link/admin/v1/user/login/*
                    method: "*"
                  - path: /api/short-link/admin/v1/user/has-username/*
                    method: "*"
                  - path: /api/short-link/admin/v1/user
                    method: "POST"
        - id: short-link-core
          uri: lb://short-link-core/api/short-link/**
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: TokenValidate