server:
  port: 8000
spring:
  application:
    name: shortlink-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: shortlink-admin
          uri: lb://shortlink-admin/api/shortlink/admin/**
          predicates:
            - Path=/api/shortlink/admin/**
          filters:
            - name: TokenValidate
              args:
                whiteList:
                  - path: /api/shortlink/admin/v1/user/login/*
                    method: "*"
                  - path: /api/shortlink/admin/v1/user/hasUserName/*
                    method: "*"
                  - path: /api/shortlink/admin/v1/user
                    method: "POST"
        - id: shortlink-core
          uri: lb://shortlink-core/api/shortlink/**
          predicates:
            - Path=/api/shortlink/**
          filters:
            - name: TokenValidate
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"