server:
  port: 8000
spring:
  application:
    name: shortlink-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: shortlink-admin
          uri: lb://shortlink-admin/api/shortlink/admin/**
          predicates:
            - Path=/api/shortlink/admin/**
          filters:
            - name: TokenValidate
              args:
                whiteList:
                  - path: /api/shortlink/admin/v1/user/login/*
                    method: "*"
                  - path: /api/shortlink/admin/v1/user/has-username/*
                    method: "*"
                  - path: /api/shortlink/admin/v1/user
                    method: "POST"
        - id: shortlink-core
          uri: lb://shortlink-core/api/shortlink/**
          predicates:
            - Path=/api/shortlink/**
          filters:
            - name: TokenValidate