server:
  port: 8002

spring:
  application:
    name: shortlink-admin
  profiles:
    active: dev
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-compose.yaml

shortlink:
  max-retry: 5
  enable-register: false
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
