server:
  port: 8001

spring:
  application:
    name: shortlink-core
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: "127.0.0.1"
      port: 6379
      password: "123456"
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

shortlink:
  max-retry: 10
  stats:
    locale:
      amap-key: 9249893b483cc314e84a09f8bec93f63
  white-list:
    enable: true
    name: '拿个offer,知乎,掘金,博客园'
    domains:
      - nageoffer.com
      - zhihu.com
      - juejin.cn
      - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml