server:
  port: 8001

spring:
  application:
    name: shortlink-core
  profiles:
    active: dev
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-compose.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html

shortlink:
  max-retry: 10
  stats:
    locale:
      amap-key: 9249893b483cc314e84a09f8bec93f63
  white-list:
    enable: false
    name: '拿个offer,知乎,掘金,博客园'
    domains:
      - baidu.com
      - zhihu.com
      - juejin.cn
      - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
